### ISSUE TITLE
KeyError: 'app_msg_list'报错，请问怎么解决

### ISSUE THREAD

**Issue by yutouyes** [Zzzz0zzzZ/py-spider-for-wechat#4]
0%|                                                                                                                                    | 0/1 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "C:\D\brandnew\sys\各种杂务\公众号排查\py-spider-for-wechat-master\main.py", line 64, in run
    run_getAllUrls(
  File "C:\D\brandnew\sys\各种杂务\公众号排查\py-spider-for-wechat-master\utils\getAllUrls.py", line 83, in run_getAllUrls
    title, link, update_time = getAllUrl(page_num=page_num, start_page=page_start, fad=fad, tok=tok, headers=headers)
  File "C:\D\brandnew\sys\各种杂务\公众号排查\py-spider-for-wechat-master\utils\getAllUrls.py", line 34, in getAllUrl
    for i in dic['app_msg_list']:     # 遍历dic['app_msg_list']中所有内容
KeyError: 'app_msg_list'

**Comment by Zzzz0zzzZ** [comment]
要不就是官方改字段名了，要不就是你的token不对，没获取到正确数据😐

**Comment by Zzzz0zzzZ** [comment]
要不就是官方改字段名了，要不就是你的token不对，没获取到正确数据😐
